# Generated by Django 3.0.8 on 2020-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyeng', '0002_auto_20200716_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'слово', 'verbose_name_plural': 'слова'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='media/categories'),
        ),
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(max_length=2, verbose_name='код уровня'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='photo',
            field=models.ImageField(upload_to='media/themes'),
        ),
        migrations.AlterField(
            model_name='word',
            name='sound',
            field=models.FileField(upload_to='media/sounds'),
        ),
    ]
